### ISSUE TITLE
请问这个怎么修改最小刻度

### ISSUE THREAD

**Issue by eskyeasy** [CoderAlexande/RulerView#1]

**Comment by eskyeasy** [comment]
将刻度修改为100

**Comment by eskyeasy** [comment]
@CoderAlexande

**Comment by lanfeng0706** [comment]
设置minValue为你想要的最小刻度，注意保证defaultValue这个属性大于minValue值。

**Comment by eskyeasy** [comment]
我的意思是最小的刻度单位为100.假设最小值为0，最大值为1000.那么这之间只有10个刻度。这个需要怎么处理？

**Comment by lanfeng0706** [comment]
设置rulerMultiple参数为0.1就OK，注意Demo中rulerLable显示的数字大小为%.1f。

**Comment by eskyeasy** [comment]
按照你这个处理。刻度单位不是100。现在问题是刻度单位（两个最小刻度间隔）为100，且怎么将间距增大？
附件一直上传不了，想详细沟通一下，能提供一个邮箱么？

**Comment by lanfeng0706** [comment]
最小单位为100mm？我刚才给你提供的参数是设置最小单位为0.1。rulerMultiple这个是控制缩放比的，你调整这个参数，应该可以得到你想要的效果。

**Comment by lanfeng0706** [comment]
在rulerMultiple使用这个参数调节的时候，当然你也应该注意maxValue和minValue值的使用。不然会出问题的。
